# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-rauc-stm"
BBFILE_PATTERN_meta-rauc-stm = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-rauc-stm = "6"

LAYERDEPENDS_meta-rauc-stm = "core rauc stm-st-stm32mp"
LAYERSERIES_COMPAT_meta-rauc-stm = "scarthgap"

RAUC_KEY_FILE ?= "${LAYERDIR}/../files/rauc-example-keys/development-1.key.pem"
RAUC_CERT_FILE ?= "${LAYERDIR}/../files/rauc-example-keys/development-1.cert.pem"
RAUC_KEYRING_FILE ?= "${LAYERDIR}/../files/rauc-example-keys/ca.cert.pem"
