[system]
compatible=@@MACHINE@@
bootloader=uboot
data-directory=/data/

[keyring]
path=/etc/rauc/ca.cert.pem

[slot.rootfs.0]
device=/dev/mmcblk0p12
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/mmcblk0p13
type=ext4
bootname=B

[slot.data.0]
device=/dev/mmcblk0p14
type=ext4